[metadata]
name = "stremio-streams"
description = "Select a stream"
requirements = ["node"]

[source]
command = 'node "$STREMIO_CLI_RUNTIME_DIR/commands/streams.$STREMIO_CLI_RUNTIME_EXTENSION" "$STREMIO_MEDIA_TYPE" "$STREMIO_VIDEO_ID"'
display = "{split:\t:1}"
output = "{split:\t:0}"
no_sort = true

[ui]
input_header = "Select a stream"

[ui.remote_control]
disabled = true

[keybindings]
ctrl-c = "actions:quit-all"

[actions.quit-all]
description = "Quit Stremio CLI"
command = 'node "$STREMIO_CLI_RUNTIME_DIR/quit.$STREMIO_CLI_RUNTIME_EXTENSION"'
mode = "execute"
