[metadata]
name = "stremio-episodes"
description = "Select an episode"
requirements = ["node"]

[source]
command = 'node "$STREMIO_CLI_ROOT/src/commands/episodes.ts" "$STREMIO_SERIES_ID" "$STREMIO_SEASON"'
display = "{split:\t:1}  {split:\t:2}"
output = "{}"
no_sort = true

[ui]
input_header = "Select an episode"

[ui.remote_control]
disabled = true

[keybindings]
enter = "actions:select"
ctrl-c = "actions:quit-all"

[actions.select]
description = "Open episode"
command = 'node "$STREMIO_CLI_ROOT/src/tv.ts" episode "{split:\t:0}"'
mode = "fork"

[actions.quit-all]
description = "Quit Stremio CLI"
command = 'node "$STREMIO_CLI_ROOT/src/quit.ts"'
mode = "execute"
