[metadata]
name = "stremio-titles"
description = "Search Stremio titles"
requirements = ["node"]

[source]
command = 'node "$STREMIO_CLI_RUNTIME_DIR/commands/search.$STREMIO_CLI_RUNTIME_EXTENSION" "$STREMIO_QUERY"'
display = "{split:\t:2}  [{split:\t:1}]  {split:\t:3}"
output = "{}"

[ui]
input_header = "Select a title"

[ui.remote_control]
disabled = true

[keybindings]
enter = "actions:select"
ctrl-c = "actions:quit-all"

[actions.select]
description = "Open title"
command = 'node "$STREMIO_CLI_RUNTIME_DIR/tv.$STREMIO_CLI_RUNTIME_EXTENSION" title "{split:\t:0}" "{split:\t:1}"'
mode = "fork"

[actions.quit-all]
description = "Quit Stremio CLI"
command = 'node "$STREMIO_CLI_RUNTIME_DIR/quit.$STREMIO_CLI_RUNTIME_EXTENSION"'
mode = "execute"
